### ISSUE TITLE
絵文字を使えるようにしたい

### ISSUE THREAD

**Issue by yykk3322** [line-school2018summer/Tokyo_A_Server#7]
したい

**Comment by yykk3322** [comment]
絵文字どころか日本語もデータベースに登録できない件について色々調べました。
テーブルの文字コードはutfmb4に設定されているのですが、データベースの文字コードはそうではないことが原因のようです。

```
 mysql> show variables like 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```

データベース内の文字コード設定にlatin1が混ざっているせいで、
日本語が全て'???'になってしまっているのかと思い、
etc/my.cnfを変更することで文字コードをutfmb4に統一しようとしたのですが、
home/ec2以下以外は全て書き込み権限がないようで変更できず詰まっています。
なにか別の解決方法などご助言お願いできないでしょうか。
[参考サイト : MySQL の文字エンコーディングを utf8mb4 に変更](http://nekonenene.hatenablog.com/entry/2016/08/02/125424)

**Comment by yykk3322** [comment]
データベース、テーブルの文字セットがutf8mb4でカラム達も同様だったのでデータベースの問題ではなかったです(多分)
データベースに手打ちで日本語文字列を追加しそれをandroidアプリ側で取得したら文字化けせず成功しました。
けれどandroidアプリ側から日本語のデータを追加しようとするとどうも文字化けしてしまうので、アプリからデータベースにデータを追加する過程での問題点を探してみます。

**Comment by yykk3322** [comment]
日本語文字列の追加に関する問題は、サーバ側でMySQLに接続するときに文字セットのパラメータがないことが原因だったので、`utf-8`を指定することで解決しました。

絵文字に関しては、サーバの設定値によって起きる問題でした。クライアントと通信時にサーバ設定値`character_set_client, character_set_connection, character_set_results = utf8`を使用して解釈するため(?)日本語は上記の方法で解決しましたが絵文字はエラーが発生しました。
解決策としてサーバ側でMySQL接続時に、起動中だけサーバ既定値を上書きできるSQL文`set names utf8mb4`をサーバ立ち上げ時に実行することで解決しました。

他の設定値は`utf8`のままなのでコマンドライン上では絵文字が文字化けしますが実害がないので放置。

**Comment by itohdak** [comment]
#7
